---
kind: pipeline
type: kubernetes
name: build

trigger:
  branch:
    - master
    - branch/*
  event:
    exclude:
      - promote
      - rollback

workspace:
  path: /docker-glibc-builder

steps:
  - name: Build package
    image: docker:git
    environment:
      GLIBC_VERSION: 2.31
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      # wait for docker to start
      - sleep 3
      - cd /docker-glibc-builder
      - mkdir -p artefacts
      - docker build . --tag sgerrand/glibc-builder:$DRONE_COMMIT
      - docker run --rm --env STDOUT=1 sgerrand/glibc-builder:$DRONE_COMMIT > artefacts/glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz

  - name: Upload Github release
    image: golang:alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - cd /docker-glibc-builder
      - apk add --no-cache git openssh-client
      - go get -v github.com/tcnksm/ghr
      - ghr -r $DRONE_REPO_NAME -u $DRONE_REPO_OWNER --prerelease --delete unreleased artefacts

services:
  - name: Start Docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: signature
hmac: 5ed8b4a1a810113dff3dd4017d326dc240a818b169645b123f5599496aeed546

...
